### ISSUE TITLE
Unit 5: ML-agents Config file could not be found 

### ISSUE THREAD

**Issue by bdiptesh99** [huggingface/deep-rl-class#209]
The command for training:
!mlagents-learn ./config/ppo/SnowballTarget.yaml --env=./training-envs-executables/linux/SnowballTarget/SnowballTarget --run-id="SnowballTarget1"

gives error:
Traceback (most recent call last):
  File "/content/ml-agents/ml-agents/mlagents/trainers/cli_utils.py", line 306, in load_config
    with open(config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: './config/ppo/SnowballTarget.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/content/ml-agents/ml-agents/mlagents/trainers/learn.py", line 260, in main
    run_cli(parse_command_line())
  File "/content/ml-agents/ml-agents/mlagents/trainers/learn.py", line 52, in parse_command_line
    return RunOptions.from_argparse(args)
  File "/content/ml-agents/ml-agents/mlagents/trainers/settings.py", line 918, in from_argparse
    configured_dict.update(load_config(config_path))
  File "/content/ml-agents/ml-agents/mlagents/trainers/cli_utils.py", line 310, in load_config
    raise TrainerConfigError(f"Config file could not be found at {abs_path}.")
mlagents.trainers.exception.TrainerConfigError: Config file could not be found at /content/ml-agents/config/ppo/SnowballTarget.yaml.

**Comment by simoninithomas** [comment]
I'm closing the issue for now
