### ISSUE TITLE
Unit 7 Hands-on: Apple Silicon installation issues

### ISSUE THREAD

**Issue by sgoodfriend** [huggingface/deep-rl-class#214]
3 issues came up when going through https://huggingface.co/deep-rl-course/unit7/hands-on on Apple Silicon. 1 & 2 are here because they might just be documentation changes. 3 might require rebuilding the SoccerTwos executable so I made that a separate issue (https://github.com/huggingface/deep-rl-class/issues/215)

# 1. conda create needing python3.9
If I follow creating a conda env with python3.8, I get the following error at `pip install -e ./ml-agents`:
```
❯ pip install -e ./ml-agents
Obtaining file:///Users/sgoodfriend/ml/ml-agents/ml-agents
  Preparing metadata (setup.py) ... done
Requirement already satisfied: grpcio>=1.11.0 in /Users/sgoodfriend/miniconda3/envs/hf-marl/lib/python3.8/site-packages (from mlagents==0.31.0.dev0) (1.51.1)
Collecting h5py>=2.9.0
  Downloading h5py-3.8.0-cp38-cp38-macosx_11_0_arm64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 14.4 MB/s eta 0:00:00
Requirement already satisfied: mlagents_envs==0.31.0.dev0 in ./ml-agents-envs (from mlagents==0.31.0.dev0) (0.31.0.dev0)
Requirement already satisfied: numpy<2.0,>=1.13.3 in /Users/sgoodfriend/miniconda3/envs/hf-marl/lib/python3.8/site-packages (from mlagents==0.31.0.dev0) (1.21.2)
Requirement already satisfied: Pillow>=4.2.1 in /Users/sgoodfriend/miniconda3/envs/hf-marl/lib/python3.8/site-packages (from mlagents==0.31.0.dev0) (9.4.0)
Requirement already satisfied: protobuf>=3.6 in /Users/sgoodfriend/miniconda3/envs/hf-marl/lib/python3.8/site-packages (from mlagents==0.31.0.dev0) (4.21.12)
Requirement already satisfied: pyyaml>=3.1.0 in /Users/sgoodfriend/miniconda3/envs/hf-marl/lib/python3.8/site-packages (from mlagents==0.31.0.dev0) (6.0)
Collecting tensorboard>=1.15
  Downloading tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 34.5 MB/s eta 0:00:00
Collecting attrs>=19.3.0
  Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 7.0 MB/s eta 0:00:00
Collecting huggingface_hub~=0.8
  Downloading huggingface_hub-0.12.0-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 kB 24.2 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torch<1.9.0,>=1.6.0 (from mlagents) (from versions: 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch<1.9.0,>=1.6.0
```

I'm pretty sure Apple Silicon isn't supported before pytorch 1.9.0

It looks like from `ml-agents/setup.py` that python3.8 isn't a hard requirement, and instead setting up the conda env with python3.9 got me through the pip install steps.

# 2. grpcio needed to be installed from conda
```
❯ mlagents-learn ./config/poca/SoccerTwos.yaml --env=./training-envs-executables/SoccerTwos.exe --run-id="base" --no-graphics
Traceback (most recent call last):
  File "/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/bin/mlagents-learn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents/mlagents/trainers/learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents/mlagents/torch_utils/__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents/mlagents/torch_utils/torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents/mlagents/trainers/settings.py", line 25, in <module>
    from mlagents.trainers.cli_utils import StoreConfigFile, DetectDefault, parser
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents/mlagents/trainers/cli_utils.py", line 5, in <module>
    from mlagents_envs.environment import UnityEnvironment
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents-envs/mlagents_envs/environment.py", line 49, in <module>
    from .rpc_communicator import RpcCommunicator
  File "/Users/sgoodfriend/ml/ml-agents/ml-agents-envs/mlagents_envs/rpc_communicator.py", line 1, in <module>
    import grpc
  File "/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/lib/python3.9/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/lib/python3.9/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/Users/sgoodfriend/miniconda3/envs/hf-marl-py39/lib/python3.9/site-packages/grpc/_cython/cygrpc.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_CFRelease'
```

Workaround was to follow these instructions https://stackoverflow.com/a/73245207:
```
pip uninstall grpcio
conda install grpcio
```

**Comment by simoninithomas** [comment]
Hey there, we changed the hands-on so that you can use Python 3.9 you will not have these problems with a Python 3.9 env

**Comment by sgoodfriend** [comment]
@simoninithomas, after trying to get this to work on a Linux box instead, Python3.9 does just seem the better route to go.

I still ran into the grpcio issue even after the `conda create python=3.9`

**Comment by simoninithomas** [comment]
I'm closing this issue for now 🤗
