### ISSUE TITLE
Unit 7 - mlagents-learn is not running. protobuf package or PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION

### ISSUE THREAD

**Issue by allansuzuki** [huggingface/deep-rl-class#228]
```
(unit7-MARL) PS > python --version
Python 3.9.16
(unit7-MARL) PS > pip --version
pip 22.3.1 from C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\site-packages\pip (python 3.9)
(unit7-MARL) PS C:\Users\AllanSuzuki\PycharmProjects\unit7-MARL\ml-agents> 
```

I installed the `ml-agents` and `ml-agents-envs`, try to run `mlagents-learn` and and error appears:

```
(unit7-MARL) PS C:\Users\AllanSuzuki\PycharmProjects\unit7-MARL\ml-agents> mlagents-learn C:\Users\AllanSuzuki\PycharmProjects\unit7-MARL\ml-agents\conf
ig\poca\SoccerTwos.yaml --env=C:\Users\AllanSuzuki\PycharmProjects\unit7-MARL\ml-agents\training-envs-executables\SoccerTwos.exe --run-id="SoccerTwos" --no-graphics
Traceback (most recent call last):
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\Scripts\mlagents-learn-script.py", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\Scripts\mlagents-learn-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\trainers\learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\torch_utils\__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\torch_utils\torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\trainers\settings.py", line 25, in <module>
    from mlagents.trainers.cli_utils import StoreConfigFile, DetectDefault, parser
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\trainers\cli_utils.py", line 5, in <module>
    from mlagents_envs.environment import UnityEnvironment
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\environment.py", line 12, in <module>
    from mlagents_envs.side_channel.side_channel import SideChannel
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\side_channel\__init__.py", line 5, in <module>
    from mlagents_envs.side_channel.default_training_analytics_side_channel import (  # noqa
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\side_channel\default_training_analytics_side_channel.py", line 7, in <module>
    from mlagents_envs.communicator_objects.training_analytics_pb2 import (
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\communicator_objects\training_analytics_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

I tried to run `mlagents-learn --help`, but the same error was thrown:

```
(unit7-MARL) PS C:\Users\AllanSuzuki\PycharmProjects\unit7-MARL\ml-agents> mlagents-learn --help                                                        
Traceback (most recent call last):                                                                                                                      
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\Scripts\mlagents-learn-script.py", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\Scripts\mlagents-learn-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\importlib\metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\trainers\learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\torch_utils\__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\torch_utils\torch.py", line 6, in <module>
    from mlagents.trainers.settings import TorchSettings
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\trainers\settings.py", line 25, in <module>
    from mlagents.trainers.cli_utils import StoreConfigFile, DetectDefault, parser
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents\mlagents\trainers\cli_utils.py", line 5, in <module>
    from mlagents_envs.environment import UnityEnvironment
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\environment.py", line 12, in <module>
    from mlagents_envs.side_channel.side_channel import SideChannel
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\side_channel\__init__.py", line 5, in <module>
    from mlagents_envs.side_channel.default_training_analytics_side_channel import (  # noqa
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\side_channel\default_training_analytics_side_channel.py", line 7, in <module>
    from mlagents_envs.communicator_objects.training_analytics_pb2 import (
  File "c:\users\allansuzuki\pycharmprojects\unit7-marl\ml-agents\ml-agents-envs\mlagents_envs\communicator_objects\training_analytics_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\AllanSuzuki\anaconda3\envs\unit7-MARL\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by simoninithomas** [comment]
Hey there 👋 this is a MLAgents error you need to open an issue to mlagents repository 🤗
