### ISSUE TITLE
Training with default ppo.py fails when generating video of the agent

### ISSUE THREAD

**Issue by javiervela** [huggingface/deep-rl-class#234]
Using the default implementation of the ppo.py file (defined following "Here's what look the ppo.py final file" in the notebook),I get the following error executing `!python ppo.py --env-id="LunarLander-v2" --repo-id=" *** " --total-timesteps=50000`:
```
global_step=49584, episodic_return=-79.0126724243164
SPS: 1331
ℹ This function will save, evaluate, generate a video of your agent,
create a model card and push everything to the hub. It might take up to 1min.
This is a work in progress: if you encounter a bug, please open an issue.
Traceback (most recent call last):
  File "ppo.py", line 586, in <module>
    package_to_hub(repo_id = args.repo_id,
  File "ppo.py", line 163, in package_to_hub
    record_video(eval_env, model, video_path, video_fps)
  File "ppo.py", line 219, in record_video
    img = env.render(mode='rgb_array')
  File "/usr/local/lib/python3.8/dist-packages/gym/core.py", line 295, in render
    return self.env.render(mode, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/box2d/lunar_lander.py", line 388, in render
    from gym.envs.classic_control import rendering
  File "/usr/local/lib/python3.8/dist-packages/gym/envs/classic_control/rendering.py", line 27, in <module>
    from pyglet.gl import *
  File "/usr/local/lib/python3.8/dist-packages/pyglet/gl/__init__.py", line 244, in <module>
    import pyglet.window
  File "/usr/local/lib/python3.8/dist-packages/pyglet/window/__init__.py", line 1880, in <module>
    gl._create_shadow_window()
  File "/usr/local/lib/python3.8/dist-packages/pyglet/gl/__init__.py", line 220, in _create_shadow_window
    _shadow_window = Window(width=1, height=1, visible=False)
  File "/usr/local/lib/python3.8/dist-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyglet/window/__init__.py", line 570, in __init__
    display = pyglet.canvas.get_display()
  File "/usr/local/lib/python3.8/dist-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/usr/local/lib/python3.8/dist-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

I fixed it appending:
```python
    # Virtual display
    from pyvirtualdisplay import Display
    
    virtual_display = Display(visible=0, size=(1400, 900))
    virtual_display.start()
```

here:
```python
if __name__ == "__main__":

    < ---- HERE

    args = parse_args()
    run_name = f"{args.env_id}__{args.exp_name}__{args.seed}__{int(time.time())}"
    if args.track:
        import wandb
```

**Comment by H4sh3** [comment]
The script tries to connect to hugging faces.
You can either provide an repo-id or adjust the code to not connect to hf.

**Comment by simoninithomas** [comment]
Hey there 👋 did you run this on colab or on your computer?

**Comment by simoninithomas** [comment]
Hey there 👋 we are currently updating the course Unit 8 I keep you updated when it's ✅

**Comment by simoninithomas** [comment]
Hey there 👋 the colab has been updated I'm closing the issue 🤗
