### ISSUE TITLE
Unit 7: Environment shuts down with return code 127

### ISSUE THREAD

**Issue by Raghav-789** [huggingface/deep-rl-class#256]
I am running this unit on gradient. this is the exact error

Version information:
  ml-agents: 0.31.0.dev0,
  ml-agents-envs: 0.31.0.dev0,
  Communicator API: 1.5.0,
  PyTorch: 1.11.0+cu102
[INFO] Learning was interrupted. Please wait while the graph is generated.
Traceback (most recent call last):
  File "/root/miniconda3/envs/rl/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/learn.py", line 264, in main
    run_cli(parse_command_line())
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/learn.py", line 260, in run_cli
    run_training(run_seed, options, num_areas)
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/learn.py", line 136, in run_training
    tc.start_learning(env_manager)
  File "/notebooks/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 197, in start_learning
    raise ex
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 172, in start_learning
    self._reset_env(env_manager)
  File "/notebooks/ml-agents/ml-agents-envs/mlagents_envs/timers.py", line 305, in wrapped
    return func(*args, **kwargs)
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/trainer_controller.py", line 105, in _reset_env
    env_manager.reset(config=new_config)
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/env_manager.py", line 68, in reset
    self.first_step_infos = self._reset_env(config)
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 446, in _reset_env
    ew.previous_step = EnvironmentStep(ew.recv().payload, ew.worker_id, {}, {})
  File "/notebooks/ml-agents/ml-agents/mlagents/trainers/subprocess_env_manager.py", line 101, in recv
    raise env_exception
mlagents_envs.exception.UnityEnvironmentException: Environment shut down with return code 127.

**Comment by simoninithomas** [comment]
Hey there 👋 did you succeed to run it? It seems it's a Gradient notebook problem.

**Comment by Raghav-789** [comment]
Hey there you were right, its a gradient issue and i solved it. Thanks
