### ISSUE TITLE
Unit 8 part 1 - Still not working, when running the ppo.py script.

### ISSUE THREAD

**Issue by joaopedrosdmm** [huggingface/deep-rl-class#278]
Still not working, when running the ppo.py script.

Now it looks like there are multiple errors in the provided traceback. The first warning indicates that TensorFlow-TensorRT (TF-TRT) was unable to find TensorRT.

Int the second error It looks like the script is trying to create a Box2D environment, but is encountering an error when importing the Box2D library. This could be due to a version incompatibility between the Box2D library and the version of Python or other libraries being used.

I will try to update Box2D library to the latest version, or downgrading to a version that is compatible with the version of Python and other libraries you are using. 

Error log:

2023-04-06 11:11:36.352338: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/ppo.py", line 413, in <module>
    envs = gym.vector.SyncVectorEnv(
  File "/usr/local/lib/python3.9/dist-packages/gym/vector/sync_vector_env.py", line 34, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "/usr/local/lib/python3.9/dist-packages/gym/vector/sync_vector_env.py", line 34, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "/content/ppo.py", line 335, in thunk
    env = gym.make(env_id)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 89, in make
    cls = load(self.entry_point)
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/registration.py", line 27, in load
    mod = importlib.import_module(mod_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/gym/envs/box2d/__init__.py", line 2, in <module>
    import Box2D
  File "/usr/local/lib/python3.9/dist-packages/Box2D/__init__.py", line 20, in <module>
    from .Box2D import *
  File "/usr/local/lib/python3.9/dist-packages/Box2D/Box2D.py", line 435, in <module>
    _Box2D.RAND_LIMIT_swigconstant(_Box2D)
AttributeError: module '_Box2D' has no attribute 'RAND_LIMIT_swigconstant'

_Originally posted by @joaopedrosdmm in https://github.com/huggingface/deep-rl-class/issues/272#issuecomment-1498906157_

**Comment by joaopedrosdmm** [comment]
Hey, just solved the issue.

When installing all the packages, change "!pip install box2d", with "!pip install box2d-py==2.3.8"
