### ISSUE TITLE
TypeError: 'EnvRegistry' object is not iterable

### ISSUE THREAD

**Issue by hariprasath28AI** [huggingface/deep-rl-class#295]
!python train.py --algo dqn --env SpaceInvadersNoFrameskip-v4 -f logs/
ERROR:
Traceback (most recent call last):
  File "/content/rl-baselines3-zoo/train.py", line 1, in <module>
    from rl_zoo3.train import train
  File "/content/rl-baselines3-zoo/rl_zoo3/__init__.py", line 6, in <module>
    import rl_zoo3.gym_patches  # noqa: F401
  File "/content/rl-baselines3-zoo/rl_zoo3/gym_patches.py", line 82, in <module>
    patched_registry.update(gym.envs.registration.registry)
TypeError: 'EnvRegistry' object is not iterable

**Comment by bhadreshpsavani** [comment]
HI @hariprasath28AI,
You can clone specific repo like `!git clone https://github.com/DLR-RM/rl-baselines3-zoo --branch v1.8.0`.
This worked for me
