### ISSUE TITLE
[HANDS-ON BUG]unit 8 package_to_hub ALSA lib error

### ISSUE THREAD

**Issue by alex-x-sun** [huggingface/deep-rl-class#404]
# Describe the bug

The model trains normally, but the package_to_hub process stuck with the following message:

ℹ This function will save, evaluate, generate a video of your agent,
create a model card and push everything to the hub. It might take up to 1min.
This is a work in progress: if you encounter a bug, please open an issue.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default

The code cell keeps running but no output. I got an empty repo on my Huggingface model page.

**notebook link (https://colab.research.google.com/drive/1MGCzYP8xor306Pr3u8-LnUav7N--tBoy?usp=sharing)**

# Material

 - Did you use Google Colab?
 - Yes. I also tried different runtime setting, CPU/GPU, high/normal RAM

**Comment by xudongmit** [comment]
If I quote the "generate video" lines in package_to_hub() function, it will work.

    # Step 4: Generate a video
    #video_path =  tmpdirname / "replay.mp4"
    #record_video(eval_env, model, video_path, video_fps) 

Although it looks messy and has no video on my Huggingface page. But at least I have a model uploaded. I'm curious what goes wrong with the record_video function? Thanks!

**Comment by simoninithomas** [comment]
Hey there 👋 that's weird I just tried and it worked. Did you run all the cells?

**Comment by dbailleul** [comment]
Hello !
Having the same problem here with Unit 8: training done but export do not work:
```
ℹ This function will save, evaluate, generate a video of your agent,
create a model card and push everything to the hub. It might take up to 1min.
This is a work in progress: if you encounter a bug, please open an issue.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (600, 400) to (608, 400) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0x638d380] Warning: data is not aligned! This can lead to a speed loss
ℹ Pushing repo ppo-LunarLander-v2-unit8 to the Hugging Face Hub
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 270, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/ppo-LunarLander-v2-unit8/preupload/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/ppo.py", line 590, in <module>
    package_to_hub(
  File "/content/ppo.py", line 179, in package_to_hub
    repo_url = upload_folder(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 1045, in _inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 4138, in upload_folder
    commit_info = self.create_commit(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 1045, in _inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 3195, in create_commit
    self.preupload_lfs_files(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 3648, in preupload_lfs_files
    _fetch_upload_modes(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_commit_api.py", line 488, in _fetch_upload_modes
    hf_raise_for_status(resp)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py", line 320, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6582ea3d-67119f9514bab59732918038;9ea84818-4219-42d1-a199-d8d9cdeb9d6f)

Repository Not Found for url: https://huggingface.co/api/models/ppo-LunarLander-v2-unit8/preupload/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Note: Creating a commit assumes that the repo already exists on the Huggingface Hub. Please use `create_repo` if it's not the case.
```

The command I used for this is
```
!python ppo.py --env-id="LunarLander-v2" --repo-id="ppo-LunarLander-v2-unit8" --total-timesteps=50000
```
So repo-id is ok and I've generated the repo-url which is correct too.
It's like it's taking my repo-id and putting it into the url of the model from Thomas here:
https://huggingface.co/api/models/ppo-LunarLander-v2-unit8/preupload/main
But it cannot work, of course... because it should be the env-id.

Any idea what is happening?
