### ISSUE TITLE
I am getting Runtime erro when I try to access leaderboard after completing the hands-on 

### ISSUE THREAD

**Issue by valmetisrinivas** [huggingface/deep-rl-class#441]
I have re-run my first hands-on exercise, Lunar Lander a few times. I am trying to access the leaderboard to check my position. However, I am getting the run time error as shown in the picture for the last several days. How can I resolve this issue?
![image](https://github.com/huggingface/deep-rl-class/assets/51160232/8c1232b4-af09-414b-87a9-a03ab551d21c)

**Comment by simoninithomas** [comment]
Hey there 👋 , we just restarted the leaderboard thanks for pointing this out.

**Comment by simoninithomas** [comment]
It works now: https://huggingface.co/spaces/huggingface-projects/Deep-Reinforcement-Learning-Leaderboard

**Comment by valmetisrinivas** [comment]
Thanks a lot.  I have noted that it is working😀.  Thanks again.

Reg,
Srinivas

**Comment by singhsegv** [comment]
I am facing the same issue with a different error:

```
403 Forbidden: Forbidden: pass `create_pr=1` as a query parameter to create a Pull Request.
Cannot access content at: https://huggingface.co/api/datasets/huggingface-projects/drlc-leaderboard-data/commit/main.
Make sure your token has the correct permissions.
```

**Comment by RockyAZ** [comment]
HEY, DO SOMETHING! It doesn't work for me either(

Full log:
```

runtime error
Exit code: 1. Reason: for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/datasets/huggingface-projects/drlc-leaderboard-data/commit/main

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 335, in <module>
    run_update_dataset()
  File "/home/user/app/app.py", line 315, in run_update_dataset
    api.upload_folder(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1524, in _inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 4677, in upload_folder
    commit_info = self.create_commit(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1524, in _inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 4053, in create_commit
    hf_raise_for_status(commit_resp, endpoint_name="commit")
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 468, in hf_raise_for_status
    raise _format(HfHubHTTPError, message, response) from e
huggingface_hub.errors.HfHubHTTPError: (Request ID: Root=1-67a84d5c-0a35e1c00660f7dd47fc3850;3e5a3747-4a14-485f-861d-dcdd06f2904c)

403 Forbidden: Forbidden: pass `create_pr=1` as a query parameter to create a Pull Request.
Cannot access content at: https://huggingface.co/api/datasets/huggingface-projects/drlc-leaderboard-data/commit/main.
Make sure your token has the correct permissions.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 335, in <module>
    run_update_dataset()
  File "/home/user/app/app.py", line 315, in run_update_dataset
    api.upload_folder(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1524, in _inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 4677, in upload_folder
    commit_info = self.create_commit(
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 1524, in _inner
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 4053, in create_commit
    hf_raise_for_status(commit_resp, endpoint_name="commit")
  File "/usr/local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 468, in hf_raise_for_status
    raise _format(HfHubHTTPError, message, response) from e
huggingface_hub.errors.HfHubHTTPError: (Request ID: Root=1-67a84d5c-0a35e1c00660f7dd47fc3850;3e5a3747-4a14-485f-861d-dcdd06f2904c)

403 Forbidden: Forbidden: pass `create_pr=1` as a query parameter to create a Pull Request.
Cannot access content at: https://huggingface.co/api/datasets/huggingface-projects/drlc-leaderboard-data/commit/main.**_

```

**Comment by ezavarygin** [comment]
@simoninithomas would you mind restarting it again? 

Related issues: 
- https://github.com/huggingface/deep-rl-class/issues/605
- https://github.com/huggingface/deep-rl-class/issues/598
- https://github.com/huggingface/deep-rl-class/issues/593
