### ISSUE TITLE
Unit 1: Part : Train our agent

### ISSUE THREAD

**Issue by 1716285375** [huggingface/deep-rl-class#565]
**!agents-learn ./config/ppo/Huggy.yaml --env=./trained-envs-executables/linux/Huggy/Huggy --run-id="Huggy1" --no-graphics**
when I **run the command** in codlab above, it comes to some erros. And I don't know how to solve it.
`
Traceback (most recent call last):
  File "/usr/local/bin/mlagents-learn", line 33, in <module>
    sys.exit(load_entry_point('mlagents', 'console_scripts', 'mlagents-learn')())
  File "/usr/local/bin/mlagents-learn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/ml-agents/ml-agents/mlagents/trainers/learn.py", line 2, in <module>
    from mlagents import torch_utils
  File "/content/ml-agents/ml-agents/mlagents/torch_utils/__init__.py", line 1, in <module>
    from mlagents.torch_utils.torch import torch as torch  # noqa
  File "/content/ml-agents/ml-agents/mlagents/torch_utils/torch.py", line 63, in <module>
    set_torch_config(TorchSettings(device=None))
  File "/content/ml-agents/ml-agents/mlagents/torch_utils/torch.py", line 56, in set_torch_config
    torch.set_default_dtype(torch.cuda.FloatTensor)
  File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 1009, in set_default_dtype
    _C._set_default_dtype(d)
TypeError: invalid dtype object: only floating-point types are supported as the default type
`
Is there any one can help me? If you can solve this question , please comment it. I will appeciate you!

**Comment by Nagi-ovo** [comment]
Always check if anyone else has encountered the same problem :)
https://github.com/huggingface/deep-rl-class/issues/560#issuecomment-2336824183

**Comment by zayneb761** [comment]
i'm having another problem in that same line, the error : 
Traceback (most recent call last):
  File "/content/ml-agents/ml-agents/mlagents_env/lib/python3.10/site-packages/mlagents/trainers/cli_utils.py", line 322, in load_config
    with open(config_path) as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config/ppo/Huggy.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/ml-agents/ml-agents/mlagents_env/bin/mlagents-learn", line 8, in <module>
    sys.exit(main())
  File "/content/ml-agents/ml-agents/mlagents_env/lib/python3.10/site-packages/mlagents/trainers/learn.py", line 270, in main
    run_cli(parse_command_line())
  File "/content/ml-agents/ml-agents/mlagents_env/lib/python3.10/site-packages/mlagents/trainers/learn.py", line 56, in parse_command_line
    return RunOptions.from_argparse(args)
  File "/content/ml-agents/ml-agents/mlagents_env/lib/python3.10/site-packages/mlagents/trainers/settings.py", line 914, in from_argparse
    configured_dict.update(load_config(config_path))
  File "/content/ml-agents/ml-agents/mlagents_env/lib/python3.10/site-packages/mlagents/trainers/cli_utils.py", line 326, in load_config
    raise TrainerConfigError(f"Config file could not be found at {abs_path}.")
mlagents.trainers.exception.TrainerConfigError: Config file could not be found at /content/ml-agents/ml-agents/config/ppo/Huggy.yaml.
